# This is a basic workflow to help you get started with Actions

name: Security Vulnerabilities Scanner

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2.3.4
    - name: Security Scanner ZAP Scan
      uses: zaproxy/action-baseline@v0.4.0
      with:
          target: 'https://tt.wipayfinancial.com/' # Target url for the scan
    - name: Create sarif file from zaproxy results
      uses: SvanBoxel/zaproxy-to-ghas@main
    - name: Upload SARIF file
      uses: github/codeql-action/upload-sarif@v1
      with:
          sarif_file: results.sarif
